spring:
    profiles:
        active:
        - ${ENVIRONMENT}
    data:
        mongodb:
            uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_SERVER}:27017
            database: valens

server:
  port: ${PORT}