apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      containers:
      - name: mongo-api
        image: parth262/mongo-crud-sample:v1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8081
          name: api
        env:
          - name: PORT
            value: "8081"
          - name: ENVIRONMENT
            value: dev
          - name: MONGO_SERVER
            value: mongo-server
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
                optional: false
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
                optional: false